### ISSUE TITLE
Update README bundling for zbar-wasm v0.10.0

### ISSUE THREAD

**Issue by iBobik** [undecaf/barcode-detector-polyfill#14]
Currently instructions needs to update on how to use bundled-in or inlined zbar.wasm introduced in zbar-wasm v0.10.0.

https://github.com/undecaf/zbar-wasm/issues/11

**Comment by undecaf** [comment]
As the current version of barcode-detector-polyfill depends on zbar-wasm 0.9.15 there is nothing wrong with the documentation as it is.

But I do agree that barcode-detector-polyfill should be updated to use zbar-wasm 0.10 and that then the docs must be updated, too. I will be on vacation next week (yes, one more time) and will work on that afterwards.

**Comment by iBobik** [comment]
> I will be on vacation next week (yes, one more time) and will work on that afterwards.

Nice, enjoy :-)

**Comment by iBobik** [comment]
@undecaf Hi, any progress on this?

I need it for this: https://github.com/capacitor-community/barcode-scanner/pull/276

**Comment by undecaf** [comment]
@iBobik My apologies for the lack of progress in this matter, but I am rather occupied by my bread-and-butter job right now (which I did not expect earlier). I hope that things go back to normal in two weeks.
