### ISSUE TITLE
Support for pdf-417 format

### ISSUE THREAD

**Issue by Hussseinkizz** [undecaf/barcode-detector-polyfill#19]
Hello I really like this, just curious, why doesn't this support pdf_417 format? Am not so versed in these things!

**Comment by undecaf** [comment]
This project depends on [`zbar-wasm`](https://github.com/undecaf/zbar-wasm) which in turn is based on the [ZBar Bar Code Reader](https://github.com/mchehab/zbar). Therefore, `barcode-detector-polyfill` can only read barcodes supported by the ZBar Bar Code Reader. Unfortunately, PDF-417 is not supported by that project.

**Comment by Hussseinkizz** [comment]
> This project depends on [`zbar-wasm`](https://github.com/undecaf/zbar-wasm) which in turn is based on the [ZBar Bar Code Reader](https://github.com/mchehab/zbar). Therefore, `barcode-detector-polyfill` can only read barcodes supported by the ZBar Bar Code Reader. Unfortunately, PDF-417 is not supported by that project.

So bad man, cause that format is so needed, any  work around you can suggest?

**Comment by undecaf** [comment]
I can only suggest to look for other projects that do support PDF-417 -- sorry.

**Comment by Hussseinkizz** [comment]
Ok sure, thanks!
