### ISSUE TITLE
About avoids the LGPL license issue?

### ISSUE THREAD

**Issue by preflower** [undecaf/barcode-detector-polyfill#2]
LGPL license ask for used code open-source or dynamic import;
i think user don't need use dynamic import `zbar.wasm`, because this library is open-source.

Do i have a misunderstand about LGPL license ?

reference: [GNU_Lesser_General_Public_License](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License)
Related Description: A program that contains no derivative of any portion of the Library, but is designed to work with the Library by being compiled or linked with it, is called a "work that uses the Library". Such a work, in isolation, is not a derivative work of the Library, and therefore falls outside the scope of this License.
Essentially, if it is a "work that uses the library", then it must be possible for the software to be linked with a newer version of the LGPL-covered program. The most commonly used method for doing so is to use "a suitable [shared library](https://en.wikipedia.org/wiki/Library_(computing)#Shared_libraries) mechanism for linking". Alternatively, a [statically linked library](https://en.wikipedia.org/wiki/Statically_linked_library) is allowed if either source code or linkable object files are provided.[[3]](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#cite_note-LGPL_Section_4-3)

**Comment by undecaf** [comment]
On second thought, I agree with that bundling `zbar.wasm` in the JavaScript universe can be regarded as equivalent to linking in the sense of the LGPL.
After all, I seem to have considered the LGPL to be more viral than it actually is (too much pandemic around me, I guess) ;-)
I will update the docs and the examples after Easter. Hopefully, this will make it easier to use the polyfill.
Thanks four your hint!

**Comment by preflower** [comment]
hope everything is ok 🙏🏻

**Comment by undecaf** [comment]
Closing this as there has not been any activity for some time.

Feel free to re-open if necessary.

**Comment by thegnuu** [comment]
@undecaf I am reaching out to you to see, if it would be possible to change the `zbar.wasm` license to allow bundling?

I am maintainer of the capacitor plugin https://github.com/capacitor-community/barcode-scanner and using your project within this plugin would add a great benefit to the PWA implementation, since the results of your solutions are way better than the current implementation based on `zxing-js`.

Unfortunately it is currently not really possible to use your library since it would require all users of our plugin to change their build systems which is not optimal in our case.

**Comment by undecaf** [comment]
@thegnuu I have come to agree with the comments of @preflower that bundling an LGPL-licensed work with e.g. an MIT-licensed work does not violate the LGPL, details [can be found here](https://fossa.com/blog/open-source-software-licenses-101-lgpl-license/).
So please feel free to bundle `zbar-wasm` with your project.

**Comment by undecaf** [comment]
As follow-up to my previous comment, I just published a new release with updated documentation and an example of how to bundle `zbar-wasm`.

**Comment by thegnuu** [comment]
Thank you very much @undecaf, this is great! I will have a look at it next week and try to implement it :)
