### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by chrisws** [undecaf/barcode-detector-polyfill#7]
The code at:
https://cdn.jsdelivr.net/npm/@undecaf/barcode-detector-polyfill@0.9.12/dist/index.js
Says `Copyright (c) Microsoft Corporation.` 
Is this correct or just an artefact of using typescript?

**Comment by undecaf** [comment]
AFAIK this license is included because [`tslib`](https://github.com/microsoft/tslib/blob/main/LICENSE.txt) is a `dev-dependency`. It appears quite permissive to me, so I would not expect it to be in conflict with the MIT license of this project.

**Comment by chrisws** [comment]
okay -  interesting, thanks
