### ISSUE TITLE
Chrome: Failed to execute 'getImageData' on 'OffscreenCanvasRenderingContext2D'

### ISSUE THREAD

**Issue by stereobooster** [undecaf/barcode-detector-polyfill#8]
I got this error in Chrome for image from remote server

```
Uncaught (in promise) DOMException: Failed to execute 'getImageData' on 'OffscreenCanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
    at t2 (http://localhost:3000/node_modules/.vite/deps/@undecaf_barcode-detector-polyfill.js?v=0927827e:104:41)
```

**Comment by undecaf** [comment]
You might try `<img crossorigin="anonymous">` in the markup (as in the [example](https://github.com/undecaf/barcode-detector-polyfill/blob/f3e6f9bd84fef67eeb471e885b13b4436d981589/docs/example/index.html#L47))
or `image.setAttribute('crossOrigin', 'anonymous')` on the `Image` object _before_ loading the image from the remote server.

This article presents a more in-depth explanation: https://inspirnathan.com/posts/105-fix-tainted-canvas-from-cross-origin-error/

**Comment by stereobooster** [comment]
Hey 👋 

First of all thank you for this library.

I probably poorly worded bug report. The problem is that this promise rejection isn't handled. I would expect `detect` function to reject with this error. I can make a PR to fix (I didn't check code, but it should be easy to find)

**Comment by undecaf** [comment]
Ahh... I understand now what you meant, and I have fixed `detect()` to return a rejected `Promise` in error cases.
