### ISSUE TITLE
Use offline

### ISSUE THREAD

**Issue by Levminer** [undecaf/barcode-detector-polyfill#9]
Hi!

I want to use this package offline, but it depends on the jsdeliver link.

I'm using esbuild, tried using this config to load it from the local node_modules (https://github.com/undecaf/barcode-detector-polyfill/blob/master/example/esbuild.config.js), (installed https://github.com/undecaf/zbar-wasm#readme). But I couldn't get it to work.

Thanks for the help!

**Comment by undecaf** [comment]
Branch `zbar-bundled` in this repository now demonstrates how to bundle `@undecaf/zbar-wasm` statically. This will enable you to use that package offline.

Please note that I am unsure whether this complies with the LGPL licenses that are involved.

**Comment by Levminer** [comment]
Thanks! It works. My [app](https://github.com/Levminer/authme) is licensed under GPL-3.0, so the licensing issue doesn't concern me.

**Comment by sy-filis** [comment]
Hi @undecaf, is there an easier way to use this package offline?

I think it would be helpful to support something like this:
```ts
import { BarcodeDetectorPolyfill } from "@undecaf/barcode-detector-polyfill";
```
for the default CDN-based usage, and:
```ts
import { BarcodeDetectorPolyfill } from "@undecaf/barcode-detector-polyfill/offline";
```
for an offline version using locally downloaded files.

This approach would be much clearer and cleaner than having to rely on manual replacements or bundler copy hacks.

**Comment by undecaf** [comment]
@sy-filis I agree that what you have propsed would be desirable. Basically, this would mean to inline file `zbar.wasm` automatically. However, I have not found a way to do this without using bundler voodoo. Any ideas for achieving this for various bundlers without voodoo would be very welcome.

The latest version of the [underlying bar code reader](https://github.com/undecaf/zbar-wasm) supports a more systematic way of inlining file `zbar.wasm`  but it is still not done automatically.
